export const Entities = {
    // Entidadades que representan las tablas de backend
    'Customers': 'Customers',
    'Users': 'Users',
    'ContactTypes': 'ContactTypes',
    'ContactsEmergency': 'ContactsEmergency',
    'CustomersBlocked': 'CustomersBlocked',
    'Contacts': 'Contacts',
    'UsersTypes': 'UsersTypes',
    'Devices': 'Devices',
    'Brands': 'Brands',
    'DevicePlotDeviceType': 'DevicePlotDeviceType',
    'DevicePlotHeaderTypes': 'DevicePlotHeaderTypes',
    'DevicePlotHeaders': 'DevicePlotHeaders',
    'DevicePlots': 'DevicePlots',
    'DeviceTests': 'DeviceTests',
    'DeviceTypeCommands': 'DeviceTypeCommands',
    'DeviceTypes': 'DeviceTypes',
    'DeviceUser': 'DeviceUser',
    'DriversDallas': 'DriversDallas',
    'EventDriverValidator': 'EventDriverValidator',
    'MobileUnityDrivers': 'MobileUnityDrivers',
    'CommandLog': 'CommandLog',
    'CommandPending': 'CommandPending',
    'CommandsList': 'CommandsList',
    'CommandsTosend': 'CommandsTosend',
    'Alerts': 'Alerts',
    'CentralAlerts': 'CentralAlerts',
    'CentralSilencedAlerts': 'CentralSilencedAlerts',
    'Novelties': 'Novelties',
    'NoveltyTypes': 'NoveltyTypes',
    'CarrerasCalles': 'CarrerasCalles',
    'Cities': 'Cities',
    'Departments': 'Departments',
    'Directions': 'Directions',
    'GeographicalEvents': 'GeographicalEvents',
    'GeographicalResources': 'GeographicalResources',
    'Municipios': 'Municipios',
    'Rutograma': 'Rutograma',
    'MobileUnities': 'MobileUnities',
    'MobileUnityDallasKeys': 'MobileUnityDallasKeys',
    'MobileUnityDriver': 'MobileUnityDriver',
    'MobileUnityGroups': 'MobileUnityGroups',
    'MobileUnityGroupunity': 'MobileUnityGroupunity',
    'ShareTracking': 'ShareTracking',
    'HabitosConduccion': 'HabitosConduccion',
    'MobileUnityAlerts': 'MobileUnityAlerts',
    'MobileUnityEvents': 'MobileUnityEvents',
    'MobileUnityLastEvents': 'MobileUnityLastEvents',
    'NotificationUnity': 'NotificationUnity',
    'Preoperacional': 'Preoperacional',
    'GeographicalResourceNotification': 'GeographicalResourceNotification',
    'GeographicalResourcesNotifications': 'GeographicalResourcesNotifications',
    'MobileUnityEventType': 'MobileUnityEventType',
    'Notifications': 'Notifications',
    'UserNotifications': 'UserNotifications',
    'FormStructureCustomer': 'FormStructureCustomer',
    'FuelConsumption': 'FuelConsumption',
    'ScheduledReports': 'ScheduledReports',
    'SharePreoperational': 'SharePreoperational',
    'TemporalWorks': 'TemporalWorks',
    'Works': 'Works',
    'Parameters': 'Parameters',
    'WebserviceBrand': 'WebserviceBrand',
    'WebserviceLine': 'WebserviceLine',
    'WebserviceLogs': 'WebserviceLogs',
    'WebserviceTypeMobileUnity': 'WebserviceTypeMobileUnity',
    'Consultants': 'Consultants',
    'DocumentTypes': 'DocumentTypes',
    'ModelHasPermissions': 'ModelHasPermissions',
    'ModelHasRoles': 'ModelHasRoles',
    'Permissions': 'Permissions',
    'RoleHasPermissions': 'RoleHasPermissions',
    'Roles': 'Roles',
    'Templates': 'Templates',
    'UserEmailTemplates': 'UserEmailTemplates',
    'UserScheduledEmails': 'UserScheduledEmails',
    'MobileUnityBrands': 'MobileUnityBrands',
    'MobileUnityClass': 'MobileUnityClass',
    'MobileUnityLine': 'MobileUnityLine',
    'MobileUnityStatus': 'MobileUnityStatus',
    'MobileUnityStatusHistory': 'MobileUnityStatusHistory',
    'MobileUnitySubclass': 'MobileUnitySubclass',
    'MobileUnityType': 'MobileUnityType',
    'EventTypes': 'EventTypes',
    'Logs': 'Logs',
    'Plans': 'Plans',
    'SimcardLogs': 'SimcardLogs',
    'SimcardPlan': 'SimcardPlan',
    'Simcards': 'Simcards',
    
    // Entidades llamadas desde componentes especificos 
    'Reporte general': "MobileUnityEvents",
    'Reporte horas trabajadas': "Works",
    'Reporte kilometros recorridos': "Works",
    'Reporte de velocidad promedio': "MobileUnityEvents",
    // 'Reporte geocercas': "",
    // 'Reporte de mantenimiento': "",
    // 'Reporte gerencial': "",
    // 'Reporte de certificado': "",
    // 'Reporte horas reposo': "", // ptra ruta verificar
    // 'Reporte de temperatura': "",
    // 'Reporte de conductores': "",
    'Reporte preoperacional': "Preoperacional",
    'Reporte hábitos de conducción': "MobileUnityEvents",
    'Reporte de gasolina': "FuelConsumption",
}