export const Servicios = {
  'MobileUnities':'Database/visor',
  'EventTypes':'Database/visor',
  'Departments':'Database/visor',
  'Cities':'Database/visor',
  'Customers':'Database/visor',
  'MobileUnityGroups':'Database/visor',
  'MobileUnityGroupunity':'Database/visor',
  'Devices':'Database/visor',
  'GeographicalEvents': 'Database/visor',
  'DriversDallas':'Database/visor',
  'Reporte general': 'mobileUnities/report-general',      
  'Reporte horas trabajadas': 'reports/report-hours-worked',
  'Reporte kilometros recorridos': 'reports/report-km-traveled',
  'Reporte de velocidad promedio': 'reports/report-velocity-aver',
  'Reporte geocercas': 'Map/reporte-geocerca',
  'Reporte de mantenimiento': 'mobileUnities/report-maintenance',
  // 'Reporte gerencial': '',
  'Reporte de certificado': 'pdf/report-certificate',
  'Reporte horas reposo': 'reports/report-hours-repose',
  // 'Reporte de temperatura': '',
  'Reporte de conductores': 'reports/report-drivers-dallas',
  'Reporte preoperacional': 'reports/report-preoperacional',
  'Reporte hábitos de conducción': 'mobileUnities/report-hc',
  'Reporte de gasolina': 'reports/report-fuel-consuption'
}